### ISSUE TITLE
Why can't I install this feature now

### ISSUE THREAD

**Issue by zhaoyouliang** [ckeditor/ckeditor5-paste-from-office#10]
when I input   "npm install --save @ckeditor/ckeditor5-paste-from-office",but it tips

 npm ERR! code E404
npm ERR! 404 Not Found: @ckeditor/ckeditor5-paste-from-office@latest.
why

**Comment by jodator** [comment]
@zhaoyouliang Thanks for your interest but this feature is still under development. That's why it is not published on NPM yet. 

You can follow [CKEditor 5 releases section on CKEditor blog](https://ckeditor.com/blog/?category=releases&tags=CKEditor-5).
