### ISSUE TITLE
Tests actual vs expected output is hardly readable

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-paste-from-office#14]
At the current state, unit tests (both normalization and integration tests) use the regular expect which compares two strings. While for integration tests it is somehow acceptable (because compared content is rather short), for normalization tests the output is usually unreadable:

![image](https://user-images.githubusercontent.com/1061942/45753021-ba42a680-bc17-11e8-8eb3-4cb7900b6793.png)

It will be good to employ some diffing mechanism which will highlight the parts which are different (or any other reasonable mechanism to make the output readable).

**Comment by Reinmar** [comment]
I think this may be a ckeditor5-dev ticket. Some smarter diff would be indeed more welcome.

**Comment by Reinmar** [comment]
cc @pomek

**Comment by jodator** [comment]
For that reason I've created [simple/dumb mechanism](https://github.com/ckeditor/ckeditor5-table/blob/master/tests/_utils/utils.js#L121-L133) in tables (table centric only):
![selection_046](https://user-images.githubusercontent.com/247363/45753384-f4607800-bc18-11e8-8f1c-c6bdcaee961b.png)

I would love to have something smarter (more like diffs on github). :clap:

**Comment by jodator** [comment]
@Reinmar I get annoyed by the output of the PFO tests:

![Selection_027](https://user-images.githubusercontent.com/247363/64362058-1875be80-d00e-11e9-89e6-a3cd8f1dd311.png)

Go and find what's wrong here (it's a single space).

So I've fiddle out with https://www.npmjs.com/package/js-beautify in PFO tests:

```js

const b = string => beautify.html_beautify( string, { indent_size: 2, space_in_empty_paren: true } );
expect( b( actualModel.replace( /\u00A0/g, ' ' ) ) ).to.equal( b( expectedModel ) );

if ( actualImages.length > 0 && expectedImages.length > 0 ) {
	expect( actualImages.length ).to.equal( expectedImages.length );
	expect( actualImages ).to.deep.equal( expectedImages );
}
```

and got this:
![Selection_026](https://user-images.githubusercontent.com/247363/64362174-5541b580-d00e-11e9-9b05-388751a544ef.png)

It is the similar approach I've used with tables - format the HTML string. It plays nice with the mocha's differ and we could introduce it as some test util that enhance expects:

```js
compareHTML( expected, actual );
```

ps.: It should play well with model strings (I check it with some table model structure).
