### ISSUE TITLE
Handling `h1` headers

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-paste-from-office#2]
Extracted from https://github.com/ckeditor/ckeditor5/issues/1184.

As pointed out by @wwalc in https://github.com/ckeditor/ckeditor5/issues/1184#issuecomment-409578965, pasting headers technically works (tags are correctly transformed), but since CKEditor supports `h2` to `h4` by default, `h1` is transformed into paragraph which is quite confusing.

We need to think about some reasonable solution:

- Convert Word headings one level down so Word `h1` will be transformed into `h2` (again see https://github.com/ckeditor/ckeditor5/issues/1184#issuecomment-409578965 and https://github.com/ckeditor/ckeditor5/issues/1184#issuecomment-409600655).
- If Paste from Word is enabled it could adjust the editor configuration so `h1` tags are correctly transformed.
- Leave as is and educated users about this, showing the proper way to reconfigure editor so it works with `h1`.
- Any other idea which makes sense.

**Comment by Reinmar** [comment]
I think we need to finally resolve https://github.com/ckeditor/ckeditor5-heading/issues/98. And this doesn't touch MS Word – it touches all data, all pasted content. We should resolve that thing and then check if there's anything special that we need to do for MS Word.
