### ISSUE TITLE
Support for pasting content from Google Docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-paste-from-office#20]
## Is this a bug report or feature request?

🆕 Feature request

## 💻 Version of CKEditor

CKEditor v5 @ 12.3.1

## 📋 Steps to reproduce

Like MS Word, Google Docs also produces some non-semantical markup which needs to be normalized before being inserted into CKEditor 5.

With this feature we want to introduce infrastructure to support Google Docs pasting (normalizers API) and a handful of converters, such as:

* basic text formatting (underline, strikethrough, superscripts, subscript - except bold which is extracted to ckeditor/ckeditor5-paste-from-office#74)
* font color, background color
* links
* images
* tables
* text alignment

---

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by f1ames** [comment]
I have rechecked (validated some time ago in https://github.com/ckeditor/ckeditor5/issues/1184#issuecomment-409828069) how pasting from GDocs works with the document formatted like:

![image](https://user-images.githubusercontent.com/1061942/48135039-15019180-e29c-11e8-9bc3-02212a30551b.png)

There are basically 3 things broken (comparing to what is supported when pasting from Word):

1. Entire content is bolded (as entire content is wrapped in special `<b>` tag interpreted by editor as bold). Broken on Chrome and Safari, works on Firefox (no `<b>` wrapper).
1. List are broken due to `ul > li > p` markup.
1. Images in tables are not pasted correctly but AFAIR this is not supported by the editor itself.

So to align it with what is supported now when pasting from Word, solving 1 and 2 should do the job.

**Comment by f1ames** [comment]
The issue with block content inside lists is more general one, related to any pasted or set content inside editor - https://github.com/ckeditor/ckeditor5/issues/1318.

**Comment by jodator** [comment]
> Images in tables are not pasted correctly but AFAIR this is not supported by the editor itself.

As for now no images in table.

**Comment by msamsel** [comment]
@jodator as we discussed I create a discussion topic for the normalizers:
#68.

**Comment by Reinmar** [comment]
Could we have a list here of things which work fine already and a list of tickets for things which don't work yet? Because it'd be good to close this ticket with some sort of summary.

**Comment by atullasrado** [comment]
> List are broken due to ul > li > p markup.

I came across something similar while pasting indented lists from Gmail. The indented content is not pasted at all. Would that come under the scope of this issue or does it require a new one?

**Comment by msamsel** [comment]
Those are my findings. I used [this document](https://docs.google.com/document/d/1okeDZfWEkCPzW-SGKSlfDXbLdggFL4dsUZBDJfWULxg/edit#) for testing purpose.
@Mgsy if you found something else during your testing of PfGD, then please add it to the list.

Sum up of paste from Google Docs support with features which I was able to match with CKE5 features:

### Available features, which might have some small issues:
1. Regular text is pasted
2. Headings are pasted. However `<h1>` and `<h2>` are recognized as Heading1. More details #70
3. Basic styles are working fine except bold which is not upcasted. More details and temporary workaround: #74.
4. Links are working fine
5. Font color and font background color are working. However, there is a `transparent` color on the document colors list. It might be useful to remove it during paste.
6. Tables are working with features available in the editor. So nested tables or table styles are not preserved.
7. Images are working (however there remains link to google docs)
8. Alignment feature is working fine as well

### Broken feature:
1. Font family and font size.
2. Indentation

### Worth mention issues:
1. Paste from Google Docs is not recognized for some specific content #75.

**Comment by mlewand** [comment]
All right, I have updated this issue to list all the basic features that we wanted to include in this release. Now the most important remaining thing is bold support, which has been extracted to ckeditor/ckeditor5-paste-from-office#74 and will be fixed in future release.
