### ISSUE TITLE
Additional empty paragraph added in a table cell when pasting table from Word

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-paste-from-office#39]
Extracted from #31.

When table is pasted from Word, additional empty paragraph is added on the end of each table cell:

![image](https://user-images.githubusercontent.com/1061942/48145043-47b68480-e2b2-11e8-96d3-293822660d8a.png)

when pasted looks like

![image](https://user-images.githubusercontent.com/1061942/48145257-bc89be80-e2b2-11e8-94f3-0fd9e998e48c.png)

**Comment by jodator** [comment]
@f1ames Is it only the paragraph with that styled text or every table cell have added empty `<p>`? It's not totally clear from the screenshoot (some looks OK some doesn't).

Do you have and output which is pasted to the edtior (after PFO do its job)? I wonder if we could clean this on table plugin - ie similar markup might occur when pasting from other pages or when parsing existing content.

**Comment by f1ames** [comment]
@jodator The empty `<p>` is added in every cell. However, this was an issue with markup pasted from Word having some whitespace/new line sequences which resulted in additional paragraph being added and was fixed in #28 (see [this comment](https://github.com/ckeditor/ckeditor5-paste-from-office/pull/28#issuecomment-441284332)).

**Comment by jodator** [comment]
Sweet! Thanks for info :)
