### ISSUE TITLE
Some formats in word cause images to not be pasted

### ISSUE THREAD

**Issue by ljjdi** [ckeditor/ckeditor5-paste-from-office#60]
I use word 2016 open this 
[test.docx](https://github.com/ckeditor/ckeditor5-paste-from-office/files/3367430/test.docx)
then paste to ckeditor5 image not paste

**Comment by Mgsy** [comment]
Hello, I can't reproduce your problem. 

![bug_cke5](https://user-images.githubusercontent.com/20988892/60798271-1f4c9600-a171-11e9-9ca6-e50ac3bf9213.gif)

Can you check if you can reproduce it [here](https://ckeditor.com/docs/ckeditor5/latest/features/paste-from-word.html) and if there are any errors in the console?

**Comment by ljjdi** [comment]
I use The Chinese version of word 2016 this my operation 
![ckeditor1](https://user-images.githubusercontent.com/39869196/60854386-ab72c200-a232-11e9-82bd-b8c5dab718b6.gif)

**Comment by Mgsy** [comment]
Thanks for a screencast. I can see that you experienced a bug described in this ticket - https://github.com/ckeditor/ckeditor5-paste-from-office/issues/51. 

I'll close your report as a duplicate.
