### ISSUE TITLE
CKEditor close ordered list when insert table

### ISSUE THREAD

**Issue by makeit-mh** [ckeditor/ckeditor5-paste-from-office#67]
When try to paste table into ordered list, CKEditor close list tag.

When paste:
<ol>
    <li>item 1</li>
    <li>item 2</li> 
   <table>
   <tr>Example</tr>
   </table>
</ol>

Result:
<ol>
    <li>item 1</li>
    <li>item 2</li> 
</ol>
   <table>
   <tr>Example</tr>
   </table>

**Comment by scofalik** [comment]
Lists containing tables are not yet supported at the moment. More on this here: https://github.com/ckeditor/ckeditor5-list/issues/47. We are going to provide support for that at some point but this is not our top priority now.
