### ISSUE TITLE
Focus never leaves figcaption

### ISSUE THREAD

**Issue by gustavovendramini** [ckeditor/ckeditor5-paste-from-office#85]
## Is this a bug report or feature request?

🐞 Bug report

## 💻 Version of CKEditor

ckeditor5-build-decoupled-document 12.4.0
Custom Build

## 📋 Steps to reproduce

1. Open the editor ex.: https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html
2. Don't type anything, the editor must be empty/clean.
3. Copy an image from word (only the image selected) then paste on editor.
4. Try type anything outside the figcaption, some text on editor.
5. Problem: Focus never leaves the figcaption/image.

## ✅ Expected result

Allow to type text before or after image

## ❎ Actual result

You cannot type text outside the image.

**Comment by Mgsy** [comment]
As I understand, your problem is that you can't type in the editor while it contains only an image? If so, you can create an empty paragraph before/after the image. Focus the image, then press <kbd>Shift + Enter</kbd> to create it before the image or <kbd>Enter</kbd> to create it after the image.

**Comment by gustavovendramini** [comment]
@Mgsy this way works, typing on keyboard `Shift + Enter` or `Enter`. 

But, Can I do this programmatically? I try initialize the editor with `<p></p>`, but doesn't works.

**Comment by Mgsy** [comment]
>But, Can I do this programmatically? I try initialize the editor with <p></p>, but doesn't works.

Yes, you can use [`Writer`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html). This code will insert a new paragraph after the first element in the editor.

```js
const root = editor.model.document.getRoot();

editor.model.change( writer => {

   const paragraph = writer.createElement( 'paragraph' );

   writer.insert( paragraph, root.getChild( 0 ), 'after' );
} );
```
